services:
  db:

    image: postgis/postgis:16-3.4
    
    container_name: pocket_go_db
    
    ports:
      - "${DATABASE_PORT}:5432"

    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST: ${DATABASE_HOST}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    restart: unless-stopped

volumes:
  postgres_data: